apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nutritrack

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - libretranslate.yaml
  - auth-service.yaml
  - user-profile-service.yaml
  - food-catalog-service.yaml
  - nutrient-enrichment-service.yaml
  - nevo-service.yaml
  - diary-service.yaml
  - gateway.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: nutritrack
