-- Seed nutrient education (FR-9). Content summarized from public NIH ODS / EFSA sources.
-- Not medical advice — see content_source citations and UI disclaimer.

INSERT INTO nutrient (code, display_name, category, default_unit, description, body_effects, deficiency_effects, excess_effects, common_sources, content_source) VALUES
('energy_kcal', 'Energy', 'ENERGY', 'kcal',
 'Dietary energy from food, expressed in kilocalories.',
 'Fuels basal metabolism, physical activity, and thermogenesis.',
 'Chronic underfueling can cause fatigue, loss of muscle, and impaired immune function.',
 'Sustained surplus contributes to weight gain when not matched by expenditure.',
 'All foods and beverages that contain macronutrients.',
 'https://ods.od.nih.gov/factsheets/list-all/'),

('energy_kj', 'Energy (kJ)', 'ENERGY', 'kJ',
 'Dietary energy expressed in kilojoules (1 kcal ≈ 4.184 kJ).',
 'Same physiological role as kilocalories; alternate unit system.',
 'Same as energy deficit: fatigue and loss of lean mass over time.',
 'Same as energy surplus: excess storage as body fat.',
 'Same as Energy (kcal).',
 'https://www.efsa.europa.eu/en/topics/topic/dietary-reference-values'),

('protein', 'Protein', 'MACRO', 'g',
 'Chains of amino acids used to build and repair body tissues.',
 'Supports muscle, enzymes, hormones, immune proteins, and satiety.',
 'Weakness, loss of muscle, slower wound healing, and in children impaired growth.',
 'Very high intakes may stress kidneys in people with existing kidney disease.',
 'Meat, fish, eggs, dairy, legumes, tofu, nuts.',
 'https://ods.od.nih.gov/factsheets/list-all/'),

('fat', 'Fat', 'MACRO', 'g',
 'Concentrated energy source and carrier of fat-soluble vitamins.',
 'Provides essential fatty acids, cushions organs, and supports cell membranes.',
 'Essential fatty acid deficiency is rare but can affect skin and growth.',
 'Excess energy from fat can promote weight gain; quality of fat matters.',
 'Oils, nuts, seeds, avocado, fatty fish, dairy, meats.',
 'https://ods.od.nih.gov/factsheets/Omega3FattyAcids-Consumer/'),

('saturated_fat', 'Saturated fat', 'MACRO', 'g',
 'Fat molecules with no double bonds in the fatty-acid chain.',
 'Used for energy; diets high in saturated fat can raise LDL cholesterol in many people.',
 'No classic deficiency syndrome; very low-fat diets can be hard to sustain.',
 'High intakes are linked with higher LDL cholesterol and cardiovascular risk.',
 'Butter, cheese, fatty meats, coconut oil, palm oil, baked goods.',
 'https://www.efsa.europa.eu/en/topics/topic/dietary-reference-values'),

('carbohydrates', 'Carbohydrates', 'MACRO', 'g',
 'Sugars and starches that are the body’s preferred quick energy source.',
 'Fuel the brain and working muscles; spare protein for tissue use.',
 'Very low carb intake can cause fatigue and ketosis; fiber-related issues if whole grains are also low.',
 'Excess refined carbs can displace nutrient-dense foods and raise calorie intake.',
 'Grains, fruit, starchy vegetables, legumes, dairy (lactose).',
 'https://www.efsa.europa.eu/en/topics/topic/dietary-reference-values'),

('sugars', 'Sugars', 'MACRO', 'g',
 'Mono- and disaccharides, including free and intrinsic sugars.',
 'Provide rapid energy; intrinsic sugars in whole fruit come with fiber and micronutrients.',
 'Not a classic deficiency nutrient.',
 'High free-sugar intake is linked with dental caries and excess calorie intake.',
 'Fruit, milk, sweetened drinks, desserts, honey, syrups.',
 'https://www.efsa.europa.eu/en/topics/topic/dietary-reference-values'),

('fiber', 'Fiber', 'MACRO', 'g',
 'Indigestible plant carbohydrates that support digestive health.',
 'Helps stool bulk, satiety, and can modestly improve blood lipids and glucose control.',
 'Low intake is associated with constipation and may raise long-term disease risk.',
 'Sudden large increases can cause bloating and gas; increase gradually with fluids.',
 'Whole grains, legumes, vegetables, fruit, nuts, seeds.',
 'https://ods.od.nih.gov/factsheets/list-all/'),

('salt', 'Salt', 'OTHER', 'g',
 'Sodium chloride; a major dietary source of sodium.',
 'Sodium helps fluid balance and nerve/muscle function.',
 'Severe sodium loss (e.g. heavy sweating without replacement) can cause hyponatremia symptoms.',
 'High salt intakes are linked with higher blood pressure in salt-sensitive people.',
 'Table salt, processed meats, bread, cheeses, savory snacks, sauces.',
 'https://ods.od.nih.gov/factsheets/Sodium-Consumer/'),

('sodium', 'Sodium', 'MINERAL', 'mg',
 'An essential electrolyte that regulates fluid balance.',
 'Supports nerve impulses, muscle contraction, and blood-pressure regulation.',
 'Rare from diet alone; can occur with extreme losses (vomiting, sweating).',
 'Excess is associated with elevated blood pressure and cardiovascular risk.',
 'Salt, processed foods, broths, condiments.',
 'https://ods.od.nih.gov/factsheets/Sodium-Consumer/'),

('vitamin_a', 'Vitamin A', 'VITAMIN', 'µg',
 'Fat-soluble vitamin (retinol and provitamin A carotenoids).',
 'Supports vision, immune function, and epithelial cell integrity.',
 'Night blindness and, in severe cases, xerophthalmia; higher infection risk.',
 'Hypervitaminosis A from high-dose supplements can be toxic; avoid excess in pregnancy.',
 'Liver, dairy, eggs, orange/green vegetables (beta-carotene).',
 'https://ods.od.nih.gov/factsheets/VitaminA-Consumer/'),

('vitamin_c', 'Vitamin C', 'VITAMIN', 'mg',
 'Water-soluble antioxidant also called ascorbic acid.',
 'Needed for collagen synthesis, immune function, and iron absorption from plants.',
 'Fatigue, poor wound healing; scurvy in prolonged severe deficiency.',
 'High supplemental doses may cause GI upset and kidney stones in susceptible people.',
 'Citrus, berries, peppers, kiwi, broccoli, tomatoes.',
 'https://ods.od.nih.gov/factsheets/VitaminC-Consumer/'),

('vitamin_d', 'Vitamin D', 'VITAMIN', 'µg',
 'Fat-soluble vitamin made in skin with sunlight and obtained from some foods.',
 'Helps absorb calcium and phosphorus; supports bone and muscle function.',
 'Rickets in children; osteomalacia and bone pain in adults; muscle weakness.',
 'Excess from supplements can raise blood calcium to harmful levels.',
 'Fatty fish, fortified dairy/plant milks, egg yolks; sunlight exposure.',
 'https://ods.od.nih.gov/factsheets/VitaminD-Consumer/'),

('vitamin_b12', 'Vitamin B12', 'VITAMIN', 'µg',
 'Cobalamin — a water-soluble vitamin for nerve and blood cell health.',
 'Required for red blood cell formation and DNA synthesis; maintains myelin.',
 'Megaloblastic anemia, neuropathy, fatigue; risk higher with vegan diets or low IF.',
 'No established toxicity from food; high doses are generally excreted.',
 'Meat, fish, eggs, dairy, fortified plant milks and cereals.',
 'https://ods.od.nih.gov/factsheets/VitaminB12-Consumer/'),

('calcium', 'Calcium', 'MINERAL', 'mg',
 'Mineral that builds bone and teeth and supports muscle and nerve signaling.',
 'Bone mineralization, muscle contraction, blood clotting, nerve transmission.',
 'Long-term low intake contributes to low bone mass and osteoporosis risk.',
 'Very high supplemental intake may raise kidney stone risk and interact with other minerals.',
 'Dairy, fortified plant milks, tofu set with calcium, leafy greens, sardines.',
 'https://ods.od.nih.gov/factsheets/Calcium-Consumer/'),

('iron', 'Iron', 'MINERAL', 'mg',
 'Mineral needed to make hemoglobin and myoglobin.',
 'Oxygen transport in blood and muscles; supports energy metabolism.',
 'Iron-deficiency anemia: fatigue, pallor, reduced work capacity; higher risk in menstruating people.',
 'Iron overload (e.g. hemochromatosis) damages organs; avoid high-dose supplements unless indicated.',
 'Red meat, offal, legumes, fortified cereals, spinach (non-heme; pair with vitamin C).',
 'https://ods.od.nih.gov/factsheets/Iron-Consumer/'),

('magnesium', 'Magnesium', 'MINERAL', 'mg',
 'Cofactor in hundreds of enzyme reactions.',
 'Supports muscle and nerve function, blood glucose control, and bone health.',
 'Low intake linked with muscle cramps, migraine risk, and metabolic issues in some studies.',
 'High supplemental doses can cause diarrhea; toxicity rare with normal kidney function from food.',
 'Nuts, seeds, whole grains, legumes, leafy greens, dark chocolate.',
 'https://ods.od.nih.gov/factsheets/Magnesium-Consumer/'),

('zinc', 'Zinc', 'MINERAL', 'mg',
 'Trace mineral for immune function and wound healing.',
 'Supports DNA synthesis, taste/smell, growth, and immune cell activity.',
 'Impaired taste, delayed wound healing, hair loss, higher infection risk.',
 'Chronic high supplements can cause copper deficiency and GI upset.',
 'Meat, shellfish, legumes, seeds, nuts, dairy.',
 'https://ods.od.nih.gov/factsheets/Zinc-Consumer/'),

('potassium', 'Potassium', 'MINERAL', 'mg',
 'Electrolyte that helps nerves and muscles fire and balances sodium.',
 'Supports blood-pressure regulation and normal heart rhythm.',
 'Low potassium (hypokalemia) can cause weakness, cramps, and arrhythmias.',
 'High blood potassium is dangerous for people with kidney disease — medical supervision required.',
 'Fruit, vegetables, legumes, potatoes, yogurt, fish.',
 'https://ods.od.nih.gov/factsheets/Potassium-Consumer/');

-- Simplified adult DRV-style seeds for goals engine (Phase 3). Values are indicative.
INSERT INTO nutrient_reference_intake (nutrient_code, sex, age_min, age_max, daily_amount, unit, basis) VALUES
('protein', 'MALE', 19, 50, 0.83, 'g', 'PER_KG'),
('protein', 'FEMALE', 19, 50, 0.83, 'g', 'PER_KG'),
('fiber', 'MALE', 19, 50, 35, 'g', 'FIXED'),
('fiber', 'FEMALE', 19, 50, 25, 'g', 'FIXED'),
('vitamin_c', 'MALE', 19, 50, 90, 'mg', 'FIXED'),
('vitamin_c', 'FEMALE', 19, 50, 75, 'mg', 'FIXED'),
('vitamin_d', 'MALE', 19, 50, 15, 'µg', 'FIXED'),
('vitamin_d', 'FEMALE', 19, 50, 15, 'µg', 'FIXED'),
('vitamin_b12', 'MALE', 19, 50, 2.4, 'µg', 'FIXED'),
('vitamin_b12', 'FEMALE', 19, 50, 2.4, 'µg', 'FIXED'),
('calcium', 'MALE', 19, 50, 1000, 'mg', 'FIXED'),
('calcium', 'FEMALE', 19, 50, 1000, 'mg', 'FIXED'),
('iron', 'MALE', 19, 50, 8, 'mg', 'FIXED'),
('iron', 'FEMALE', 19, 50, 18, 'mg', 'FIXED'),
('magnesium', 'MALE', 19, 50, 400, 'mg', 'FIXED'),
('magnesium', 'FEMALE', 19, 50, 310, 'mg', 'FIXED'),
('zinc', 'MALE', 19, 50, 11, 'mg', 'FIXED'),
('zinc', 'FEMALE', 19, 50, 8, 'mg', 'FIXED'),
('potassium', 'MALE', 19, 50, 3400, 'mg', 'FIXED'),
('potassium', 'FEMALE', 19, 50, 2600, 'mg', 'FIXED'),
('sodium', 'MALE', 19, 50, 2300, 'mg', 'FIXED'),
('sodium', 'FEMALE', 19, 50, 2300, 'mg', 'FIXED');
