-- Expand vitamin/mineral catalog (education + adult DRV seeds).
-- Content summarized from public NIH ODS sources; not medical advice.

INSERT INTO nutrient (code, display_name, category, default_unit, description, body_effects, deficiency_effects, excess_effects, common_sources, content_source) VALUES
('vitamin_b1', 'Vitamin B1 (Thiamine)', 'VITAMIN', 'mg',
 'Water-soluble B vitamin involved in carbohydrate energy metabolism.',
 'Supports energy metabolism and nerve function.',
 'Beriberi, fatigue, and neurological symptoms with prolonged low intake.',
 'No established toxicity from food; high supplements rarely cause issues.',
 'Whole grains, pork, legumes.',
 'https://ods.od.nih.gov/factsheets/Thiamin-Consumer/'),

('vitamin_b2', 'Vitamin B2 (Riboflavin)', 'VITAMIN', 'mg',
 'Water-soluble B vitamin that helps convert food into energy.',
 'Supports energy production and healthy skin.',
 'Sore throat, cracked lips, and skin disorders with deficiency.',
 'No established upper limit from food sources.',
 'Dairy, eggs, almonds, mushrooms.',
 'https://ods.od.nih.gov/factsheets/Riboflavin-Consumer/'),

('vitamin_b3', 'Vitamin B3 (Niacin)', 'VITAMIN', 'mg',
 'Water-soluble B vitamin (niacin / nicotinic acid / nicotinamide).',
 'Supports energy production and DNA repair.',
 'Pellagra (dermatitis, diarrhea, dementia) in severe deficiency.',
 'High-dose supplements can cause flushing and liver stress.',
 'Chicken, tuna, peanuts.',
 'https://ods.od.nih.gov/factsheets/Niacin-Consumer/'),

('vitamin_b5', 'Vitamin B5 (Pantothenic acid)', 'VITAMIN', 'mg',
 'Water-soluble B vitamin needed to make coenzyme A.',
 'Supports hormone and energy production.',
 'Rare; fatigue and numbness with extreme deficiency.',
 'Very high supplements may cause GI upset.',
 'Chicken, mushrooms, avocados.',
 'https://ods.od.nih.gov/factsheets/PantothenicAcid-Consumer/'),

('vitamin_b6', 'Vitamin B6', 'VITAMIN', 'mg',
 'Water-soluble B vitamin (pyridoxine and related forms).',
 'Supports brain function and red blood cell formation.',
 'Anemia, dermatitis, and depression-like symptoms with deficiency.',
 'Very high long-term supplements can cause neuropathy.',
 'Potatoes, bananas, poultry, fish.',
 'https://ods.od.nih.gov/factsheets/VitaminB6-Consumer/'),

('vitamin_b7', 'Vitamin B7 (Biotin)', 'VITAMIN', 'µg',
 'Water-soluble B vitamin also called vitamin H.',
 'Supports fat metabolism and healthy hair and nails.',
 'Rare; hair thinning and skin rash with deficiency.',
 'No established toxicity from food.',
 'Eggs, nuts, seeds.',
 'https://ods.od.nih.gov/factsheets/Biotin-Consumer/'),

('vitamin_b9', 'Vitamin B9 (Folate)', 'VITAMIN', 'µg',
 'Folate / folic acid — essential for one-carbon metabolism.',
 'Supports DNA synthesis; especially important in pregnancy.',
 'Megaloblastic anemia; neural-tube defect risk when low in early pregnancy.',
 'High folic acid can mask B12 deficiency.',
 'Leafy greens, beans, lentils.',
 'https://ods.od.nih.gov/factsheets/Folate-Consumer/'),

('vitamin_e', 'Vitamin E', 'VITAMIN', 'mg',
 'Fat-soluble antioxidant vitamin (tocopherols / tocotrienols).',
 'Protects cell membranes from oxidative damage.',
 'Nerve and muscle damage with prolonged severe deficiency (rare).',
 'High supplemental doses may increase bleeding risk.',
 'Nuts, seeds, vegetable oils.',
 'https://ods.od.nih.gov/factsheets/VitaminE-Consumer/'),

('vitamin_k', 'Vitamin K', 'VITAMIN', 'µg',
 'Fat-soluble vitamin needed for clotting proteins (K1 / K2 forms).',
 'Supports blood clotting and bone health.',
 'Easy bruising and bleeding with deficiency.',
 'People on warfarin need consistent intake — medical supervision.',
 'Kale, spinach, broccoli.',
 'https://ods.od.nih.gov/factsheets/VitaminK-Consumer/'),

('iodine', 'Iodine', 'MINERAL', 'µg',
 'Trace mineral required for thyroid hormone synthesis.',
 'Supports thyroid hormones and metabolic rate.',
 'Goiter and hypothyroidism risk with low intake.',
 'Excess can disrupt thyroid function in susceptible people.',
 'Iodized salt, seafood, dairy.',
 'https://ods.od.nih.gov/factsheets/Iodine-Consumer/'),

('selenium', 'Selenium', 'MINERAL', 'µg',
 'Trace mineral with antioxidant enzyme roles.',
 'Supports antioxidant defenses and thyroid function.',
 'Keshan disease / thyroid issues in severe deficiency regions.',
 'High supplemental doses can cause selenosis (hair/nail loss).',
 'Brazil nuts, seafood, eggs.',
 'https://ods.od.nih.gov/factsheets/Selenium-Consumer/'),

('copper', 'Copper', 'MINERAL', 'mg',
 'Trace mineral cofactor for many enzymes.',
 'Supports iron metabolism and connective tissue.',
 'Anemia and bone abnormalities with deficiency (uncommon).',
 'High intakes can cause GI distress and liver damage.',
 'Nuts, shellfish, liver.',
 'https://ods.od.nih.gov/factsheets/Copper-Consumer/'),

('manganese', 'Manganese', 'MINERAL', 'mg',
 'Trace mineral involved in bone and metabolism enzymes.',
 'Supports bone formation and carbohydrate metabolism.',
 'Rare from diet alone.',
 'High occupational / supplemental exposure can be neurotoxic.',
 'Whole grains, nuts, tea.',
 'https://ods.od.nih.gov/factsheets/Manganese-Consumer/'),

('phosphorus', 'Phosphorus', 'MINERAL', 'mg',
 'Mineral that forms bone mineral and high-energy phosphates (ATP).',
 'Supports bones and cellular energy.',
 'Rare with normal diets; bone weakness with prolonged low intake.',
 'High intakes may affect calcium balance in kidney disease.',
 'Dairy, meat, beans.',
 'https://ods.od.nih.gov/factsheets/Phosphorus-Consumer/'),

('chromium', 'Chromium', 'MINERAL', 'µg',
 'Trace mineral that may enhance insulin action.',
 'Supports blood sugar regulation.',
 'Impaired glucose tolerance reported in rare deficiency states.',
 'High supplemental chromium safety is uncertain long-term.',
 'Whole grains, broccoli.',
 'https://ods.od.nih.gov/factsheets/Chromium-Consumer/'),

('molybdenum', 'Molybdenum', 'MINERAL', 'µg',
 'Trace mineral cofactor for oxidase enzymes.',
 'Supports enzyme function in metabolism of sulfur compounds.',
 'Extremely rare dietary deficiency.',
 'Very high intakes may cause copper imbalance.',
 'Legumes, grains.',
 'https://ods.od.nih.gov/factsheets/Molybdenum-Consumer/');

INSERT INTO nutrient_reference_intake (nutrient_code, sex, age_min, age_max, daily_amount, unit, basis) VALUES
('vitamin_a', 'MALE', 19, 50, 900, 'µg', 'FIXED'),
('vitamin_a', 'FEMALE', 19, 50, 700, 'µg', 'FIXED'),
('vitamin_b1', 'MALE', 19, 50, 1.2, 'mg', 'FIXED'),
('vitamin_b1', 'FEMALE', 19, 50, 1.1, 'mg', 'FIXED'),
('vitamin_b2', 'MALE', 19, 50, 1.3, 'mg', 'FIXED'),
('vitamin_b2', 'FEMALE', 19, 50, 1.1, 'mg', 'FIXED'),
('vitamin_b3', 'MALE', 19, 50, 16, 'mg', 'FIXED'),
('vitamin_b3', 'FEMALE', 19, 50, 14, 'mg', 'FIXED'),
('vitamin_b5', 'MALE', 19, 50, 5, 'mg', 'FIXED'),
('vitamin_b5', 'FEMALE', 19, 50, 5, 'mg', 'FIXED'),
('vitamin_b6', 'MALE', 19, 50, 1.3, 'mg', 'FIXED'),
('vitamin_b6', 'FEMALE', 19, 50, 1.3, 'mg', 'FIXED'),
('vitamin_b7', 'MALE', 19, 50, 30, 'µg', 'FIXED'),
('vitamin_b7', 'FEMALE', 19, 50, 30, 'µg', 'FIXED'),
('vitamin_b9', 'MALE', 19, 50, 400, 'µg', 'FIXED'),
('vitamin_b9', 'FEMALE', 19, 50, 400, 'µg', 'FIXED'),
('vitamin_e', 'MALE', 19, 50, 15, 'mg', 'FIXED'),
('vitamin_e', 'FEMALE', 19, 50, 15, 'mg', 'FIXED'),
('vitamin_k', 'MALE', 19, 50, 120, 'µg', 'FIXED'),
('vitamin_k', 'FEMALE', 19, 50, 90, 'µg', 'FIXED'),
('iodine', 'MALE', 19, 50, 150, 'µg', 'FIXED'),
('iodine', 'FEMALE', 19, 50, 150, 'µg', 'FIXED'),
('selenium', 'MALE', 19, 50, 55, 'µg', 'FIXED'),
('selenium', 'FEMALE', 19, 50, 55, 'µg', 'FIXED'),
('copper', 'MALE', 19, 50, 0.9, 'mg', 'FIXED'),
('copper', 'FEMALE', 19, 50, 0.9, 'mg', 'FIXED'),
('manganese', 'MALE', 19, 50, 2.3, 'mg', 'FIXED'),
('manganese', 'FEMALE', 19, 50, 1.8, 'mg', 'FIXED'),
('phosphorus', 'MALE', 19, 50, 700, 'mg', 'FIXED'),
('phosphorus', 'FEMALE', 19, 50, 700, 'mg', 'FIXED'),
('chromium', 'MALE', 19, 50, 35, 'µg', 'FIXED'),
('chromium', 'FEMALE', 19, 50, 25, 'µg', 'FIXED'),
('molybdenum', 'MALE', 19, 50, 45, 'µg', 'FIXED'),
('molybdenum', 'FEMALE', 19, 50, 45, 'µg', 'FIXED');
